:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - default
scheduler:
  schedule:
    mark_abandoned_carts:
      cron: '0 * * * *'
      class: 'MarkCartAsAbandonedJob'
      queue: default
      description: 'Mark abandoned carts and remove old ones'
